// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One coalesced file-system event.
 *
 * Variants:
 * * `Created`  - a path that did not exist now does.
 * * `Modified` - the contents of an existing path changed (covers both raw
 *   modify events and "atomic save" delete+create bursts that collapse to
 *   a single `Modified`).
 * * `Deleted`  - a path that existed no longer does.
 * * `Renamed`  - a single `from -> to` move where both endpoints arrived
 *   within the coalescing window. If only one half arrives, the coalescer
 *   downgrades to `Deleted` (from-only) or `Created` (to-only).
 */
export type WatchEvent = { "kind": "created", path: string, } | { "kind": "modified", path: string, } | { "kind": "deleted", path: string, } | { "kind": "renamed", from: string, to: string, };
