// Generated TS bindings live in apps/desktop/src-tauri/bindings/.
// `ts-rs` regenerates them on `cargo test`; never hand-edit.
//
// Phase 1.1 ships the registry surface; Phase 2.1 extends the barrel
// with the IPC and pipeline-event wire types so the React side doesn't
// need to know about the bindings folder layout.

export type { ToolId } from "../../../apps/desktop/src-tauri/bindings/registry/ToolId";
export type { ComponentType } from "../../../apps/desktop/src-tauri/bindings/registry/ComponentType";
export type { Scope } from "../../../apps/desktop/src-tauri/bindings/registry/Scope";
export type { Format } from "../../../apps/desktop/src-tauri/bindings/registry/Format";
export type { ComponentRoot } from "../../../apps/desktop/src-tauri/bindings/registry/ComponentRoot";
export type { ToolDescriptor } from "../../../apps/desktop/src-tauri/bindings/registry/ToolDescriptor";
export type { DetectedTool } from "../../../apps/desktop/src-tauri/bindings/registry/DetectedTool";

// IPC wire types - one per command + the supporting filter/query/result
// shapes. Generated by ts-rs from `apps/desktop/src-tauri/src/ipc/types.rs`.
export type { ComponentFilter } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentFilter";
export type { ComponentSummary } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentSummary";
export type { ComponentDetail } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentDetail";
export type { SearchQuery } from "../../../apps/desktop/src-tauri/bindings/ipc/SearchQuery";
export type { SearchResult } from "../../../apps/desktop/src-tauri/bindings/ipc/SearchResult";
export type { HealthSummary } from "../../../apps/desktop/src-tauri/bindings/ipc/HealthSummary";
export type { ToolHealthCount } from "../../../apps/desktop/src-tauri/bindings/ipc/ToolHealthCount";

// Pipeline event bridge types (Tauri `pipeline-event` channel + the
// scan report returned by `start_full_scan`).
export type { PipelineEvent } from "../../../apps/desktop/src-tauri/bindings/pipeline/PipelineEvent";
export type { ScanReport } from "../../../apps/desktop/src-tauri/bindings/pipeline/ScanReport";
export type { UpsertKind } from "../../../apps/desktop/src-tauri/bindings/index/UpsertOutcome";

// Hand-rolled UI summary type used by the sidebar; not on the IPC wire.
import type { ToolId } from "../../../apps/desktop/src-tauri/bindings/registry/ToolId";

export interface ToolSummary {
  id: ToolId;
  displayName: string;
  detected: boolean;
  componentCount: number;
}
