// Generated TS bindings live in apps/desktop/src-tauri/bindings/.
// `ts-rs` regenerates them on `cargo test`; never hand-edit.
//
// Phase 1.1 ships the registry surface; Phase 2.1 extends the barrel
// with the IPC and pipeline-event wire types so the React side doesn't
// need to know about the bindings folder layout.

export type { ToolId } from "../../../apps/desktop/src-tauri/bindings/registry/ToolId";
export type { ComponentType } from "../../../apps/desktop/src-tauri/bindings/registry/ComponentType";
export type { Scope } from "../../../apps/desktop/src-tauri/bindings/registry/Scope";
export type { Format } from "../../../apps/desktop/src-tauri/bindings/registry/Format";
export type { ComponentRoot } from "../../../apps/desktop/src-tauri/bindings/registry/ComponentRoot";
export type { ToolDescriptor } from "../../../apps/desktop/src-tauri/bindings/registry/ToolDescriptor";
export type { DetectedTool } from "../../../apps/desktop/src-tauri/bindings/registry/DetectedTool";

// IPC wire types - one per command + the supporting filter/query/result
// shapes. Generated by ts-rs from `apps/desktop/src-tauri/src/ipc/types.rs`.
export type { ComponentFilter } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentFilter";
export type { ComponentSummary } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentSummary";
export type { ComponentDetail } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentDetail";
export type { SearchQuery } from "../../../apps/desktop/src-tauri/bindings/ipc/SearchQuery";
export type { SearchResult } from "../../../apps/desktop/src-tauri/bindings/ipc/SearchResult";
export type { HealthSummary } from "../../../apps/desktop/src-tauri/bindings/ipc/HealthSummary";
export type { ToolHealthCount } from "../../../apps/desktop/src-tauri/bindings/ipc/ToolHealthCount";
export type { IpcError } from "../../../apps/desktop/src-tauri/bindings/ipc/IpcError";

// Phase 3.3 - Editor save flow.
export type { SaveOutcome } from "../../../apps/desktop/src-tauri/bindings/ipc/SaveOutcome";
export type { ComponentDetailWithRaw } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentDetailWithRaw";

// Phase 3.2 - validator surface (re-exported here for the Editor form).
export type { ValidationError } from "../../../apps/desktop/src-tauri/bindings/validator/ValidationError";
export type { ValidationOutcome } from "../../../apps/desktop/src-tauri/bindings/validator/ValidationOutcome";
export type { ValidationWarning } from "../../../apps/desktop/src-tauri/bindings/validator/ValidationWarning";
export type { ValidationWarningKind } from "../../../apps/desktop/src-tauri/bindings/validator/ValidationWarningKind";

// Phase 7.3: Security view wire types.
export type { Severity } from "../../../apps/desktop/src-tauri/bindings/security/Severity";
export type { Category as SecurityCategory } from "../../../apps/desktop/src-tauri/bindings/security/Category";
export type { Finding } from "../../../apps/desktop/src-tauri/bindings/security/Finding";
export type { SecurityFilter } from "../../../apps/desktop/src-tauri/bindings/ipc/SecurityFilter";
export type { FindingSummary } from "../../../apps/desktop/src-tauri/bindings/ipc/FindingSummary";
export type { SeverityCounts } from "../../../apps/desktop/src-tauri/bindings/ipc/SeverityCounts";
export type { ComponentFindingsCount } from "../../../apps/desktop/src-tauri/bindings/ipc/ComponentFindingsCount";
export type { SecurityCategoryCounts } from "../../../apps/desktop/src-tauri/bindings/ipc/SecurityCategoryCounts";
export type { SecuritySummary } from "../../../apps/desktop/src-tauri/bindings/ipc/SecuritySummary";

// Pipeline event bridge types (Tauri `pipeline-event` channel + the
// scan report returned by `start_full_scan`).
export type { PipelineEvent } from "../../../apps/desktop/src-tauri/bindings/pipeline/PipelineEvent";
export type { ScanReport } from "../../../apps/desktop/src-tauri/bindings/pipeline/ScanReport";
export type { UpsertKind } from "../../../apps/desktop/src-tauri/bindings/index/UpsertOutcome";

// Phase 6.2: auto-update wire types. The frontend listens for the
// `update-available` Tauri event (payload: `UpdateAvailable`) and
// surfaces the IPC commands that toggle channel + auto-check.
export type { UpdateAvailable } from "../../../apps/desktop/src-tauri/bindings/updates/UpdateAvailable";
export type { UpdateChannel } from "../../../apps/desktop/src-tauri/bindings/updates/UpdateChannel";
export type { UpdateError } from "../../../apps/desktop/src-tauri/bindings/updates/UpdateError";

// Phase 14C: token usage / cost view wire types. The frontend Cost view
// consumes `usage_query` and `usage_refresh`; every payload type lives
// under `bindings/usage/`.
export type { CostQuery } from "../../../apps/desktop/src-tauri/bindings/usage/CostQuery";
export type { CostResponse } from "../../../apps/desktop/src-tauri/bindings/usage/CostResponse";
export type { SummaryResponse } from "../../../apps/desktop/src-tauri/bindings/usage/SummaryResponse";
export type { ByProjectRow } from "../../../apps/desktop/src-tauri/bindings/usage/ByProjectRow";
export type { ByDayRow } from "../../../apps/desktop/src-tauri/bindings/usage/ByDayRow";
export type { CostRec } from "../../../apps/desktop/src-tauri/bindings/usage/CostRec";
export type { CostRecKind } from "../../../apps/desktop/src-tauri/bindings/usage/CostRecKind";
export type { TokenTotals } from "../../../apps/desktop/src-tauri/bindings/usage/TokenTotals";
export type { PriceLookup } from "../../../apps/desktop/src-tauri/bindings/usage/PriceLookup";
export type { ToolKind as UsageToolKind } from "../../../apps/desktop/src-tauri/bindings/usage/UsageToolKind";

// Phase 15: backup + restore wire types. The Settings -> Backup pane
// consumes `backup_now`, `restore_now`, `backup_status`, and
// `backup_set_auto`; every payload type lives under `bindings/backup/`.
export type { BackupReport } from "../../../apps/desktop/src-tauri/bindings/backup/BackupReport";
export type { BackupErrorEntry } from "../../../apps/desktop/src-tauri/bindings/backup/BackupErrorEntry";
export type { BackupErrorKind } from "../../../apps/desktop/src-tauri/bindings/backup/BackupErrorKind";
export type { BackupStatusReport } from "../../../apps/desktop/src-tauri/bindings/backup/BackupStatus";
export type { RestoreReport } from "../../../apps/desktop/src-tauri/bindings/backup/RestoreReport";
export type { RestoreErrorEntry } from "../../../apps/desktop/src-tauri/bindings/backup/RestoreErrorEntry";
export type { RestoreErrorKind } from "../../../apps/desktop/src-tauri/bindings/backup/RestoreErrorKind";
export type { VerifyReport } from "../../../apps/desktop/src-tauri/bindings/backup/VerifyReport";
export type { VerifyErrorEntry } from "../../../apps/desktop/src-tauri/bindings/backup/VerifyErrorEntry";
export type { VerifyErrorKind } from "../../../apps/desktop/src-tauri/bindings/backup/VerifyErrorKind";

// Phase 17: projects view + actions wire types.
export type { ProjectSummary } from "../../../apps/desktop/src-tauri/bindings/projects/ProjectSummary";
export type { MemoryFileSummary } from "../../../apps/desktop/src-tauri/bindings/projects/MemoryFileSummary";
export type { MemoryAnalysisReport } from "../../../apps/desktop/src-tauri/bindings/projects/MemoryAnalysisReport";
export type { MemoryRecommendation } from "../../../apps/desktop/src-tauri/bindings/projects/MemoryRecommendation";
export type { MemoryRecommendationKind } from "../../../apps/desktop/src-tauri/bindings/projects/MemoryRecommendationKind";
export type { WorktreeReport } from "../../../apps/desktop/src-tauri/bindings/projects/WorktreeReport";
export type { WorktreeEntry } from "../../../apps/desktop/src-tauri/bindings/projects/WorktreeEntry";

// Hand-rolled UI summary type used by the sidebar; not on the IPC wire.
import type { ToolId } from "../../../apps/desktop/src-tauri/bindings/registry/ToolId";

export interface ToolSummary {
  id: ToolId;
  displayName: string;
  detected: boolean;
  componentCount: number;
}
