// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenTotals } from "./TokenTotals";

/**
 * One row in `kind = "byProject"`.
 */
export type ByProjectRow = { project: string, costUsd: number, tokens: TokenTotals, };
