// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostRecKind } from "./CostRecKind";

/**
 * One recommendation - what to fix, why, and an estimated 30-day
 * savings figure.
 */
export type CostRec = { kind: CostRecKind, title: string, rationale: string, estimatedSavingsUsd30d: number, 
/**
 * Component IDs the UI should expose as "open in editor" links.
 */
relatedComponents: Array<string>, 
/**
 * The project these savings are tied to (decoded cwd).
 */
projectPath: string, };
