// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ByDayRow } from "./ByDayRow";
import type { ByProjectRow } from "./ByProjectRow";
import type { CostRec } from "./CostRec";
import type { SummaryResponse } from "./SummaryResponse";

/**
 * Tagged union returned by `usage_query`. Mirrors the spec's
 * `CostResponse` shape.
 */
export type CostResponse = { "kind": "summary" } & SummaryResponse | { "kind": "byProject", rows: Array<ByProjectRow>, } | { "kind": "byDay", rows: Array<ByDayRow>, } | { "kind": "recommendations", recs: Array<CostRec>, };
