// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * IPC discriminator. Mirrors the spec's `CostQuery` literal union.
 */
export type CostQuery = "summary" | "byProject" | "byDay" | "recommendations";
