// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three recommendation flavours. Serialised as camelCase strings so
 * the UI can switch on a stable discriminator.
 */
export type CostRecKind = "bloatedMemory" | "lowCacheHitRate" | "oldModelOnHotProject";
