// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of [`lookup_price`].
 */
export type PriceLookup = { inputPerM: number, outputPerM: number, cacheReadPerM: number, cacheCreatePerM: number, 
/**
 * `true` when the model id matched a known prefix; `false` when
 * the lookup fell through to the default. The UI footnotes
 * uncertain rows.
 */
modelKnown: boolean, };
