// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenTotals } from "./TokenTotals";

/**
 * Headline summary returned by `kind = "summary"`.
 */
export type SummaryResponse = { tokens30d: TokenTotals, costUsd30d: number, topProject: string, topProjectCost: number, 
/**
 * `refreshed_at` of the most-recent row read. 0 when the table
 * is empty.
 */
refreshedAt: bigint, };
