// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenTotals } from "./TokenTotals";

/**
 * Headline summary returned by `kind = "summary"`.
 */
export type SummaryResponse = { tokens30d: TokenTotals, costUsd30d: number, topProject: string, topProjectCost: number, 
/**
 * `refreshed_at` of the most-recent row read. 0 when the table
 * is empty.
 */
refreshedAt: bigint, 
/**
 * Snapshot identifier of the price table used to compute
 * `cost_usd_30d`. Surfaced verbatim in the Cost view footer so
 * the UI cannot drift from the actual prices that were applied.
 */
priceTableVersion: string, };
