// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Folded token totals for an arbitrary slice (one row, one project,
 * one day, ...). Carries the four usage buckets the UI displays.
 */
export type TokenTotals = { input: bigint, output: bigint, cacheRead: bigint, cacheCreate: bigint, };
