// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tool produced a usage row. The serialised string lands in
 * the `token_usage.tool` column verbatim.
 */
export type ToolKind = "claude-code" | "codex";
