// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { Scope } from "../registry/Scope";
import type { ToolId } from "../registry/ToolId";

/**
 * Filter sent by the React UI to `list_components`.
 *
 * All fields are optional; an empty filter returns the first
 * `limit` components ordered by `mtime DESC`.
 */
export type ComponentFilter = { toolId: ToolId | null, kind: ComponentType | null, scope: Scope | null, 
/**
 * Substring match against `name` and `description`. Implemented
 * via `LIKE` so it does NOT use FTS - that is the dedicated
 * `search` command's job.
 */
query: string | null, 
/**
 * Filter by user-applied tag.
 */
tag: string | null, 
/**
 * Page size. Default 200; clamped to 1000 server-side.
 */
limit: number | null, 
/**
 * Offset into the result set (default 0).
 */
offset: number | null, 
/**
 * Audit issue #8: lower-bound `mtime` cutoff (unix seconds). When
 * set, only rows whose `mtime >= modified_after_unix` are
 * returned. Drives the inventory `last:Nd` / `last:Nh` / `last:Nw`
 * filter chip; the parser converts `Nd`/`Nh`/`Nw` into the
 * concrete cutoff before this hits the wire.
 */
modifiedAfterUnix: bigint | null, };
