// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { Format } from "../registry/Format";
import type { Scope } from "../registry/Scope";
import type { ToolId } from "../registry/ToolId";

/**
 * Full row returned by `get_component`.
 */
export type ComponentDetail = { 
/**
 * JSON-encoded parsed content. Schema depends on `format`.
 */
parsedJson: string | null, 
/**
 * JSON-encoded parse error metadata, when `has_parse_errors`.
 */
parseErrors: string | null, origin: string, pluginId: string | null, id: string, name: string, displayName: string | null, description: string | null, kind: ComponentType, tool: ToolId, scope: Scope, format: Format, path: string, size: bigint, mtime: bigint, hash: string, hasParseErrors: boolean, lastUsedAt: bigint | null, useCount: number, };
