// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { Format } from "../registry/Format";
import type { Scope } from "../registry/Scope";
import type { ToolId } from "../registry/ToolId";

/**
 * One entry in a `list_components` result.
 *
 * Lightweight by design: full parsed content lives behind
 * `get_component`. `ComponentSummary` is what populates Inventory
 * rows, sidebar facets, and the Map view nodes.
 */
export type ComponentSummary = { id: string, name: string, displayName: string | null, description: string | null, kind: ComponentType, tool: ToolId, scope: Scope, format: Format, path: string, size: bigint, mtime: bigint, hash: string, hasParseErrors: boolean, lastUsedAt: bigint | null, useCount: number, };
