// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeverityCounts } from "./SeverityCounts";

/**
 * One row returned by `get_findings_count_per_component`.
 */
export type ComponentFindingsCount = { componentId: string, total: number, bySeverity: SeverityCounts, };
