// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentDetail } from "./ComponentDetail";

/**
 * One-trip Editor open payload combining `get_component` with the
 * raw on-disk text.
 *
 * Phase 3.3 introduces this so the Editor view can populate Monaco +
 * the form pane in a single round-trip rather than two
 * (`get_component` followed by `read_component_raw`). The two earlier
 * commands stay because Quick Look + the Inventory previewer still
 * only need one of them.
 */
export type ComponentDetailWithRaw = { 
/**
 * The same shape `get_component` returns.
 */
detail: ComponentDetail, 
/**
 * Raw UTF-8 bytes off disk - what Monaco edits.
 */
raw: string, 
/**
 * SHA-256 (hex) snapshot of `raw` at open time. The editor
 * hands this back on save so the backend can detect external
 * changes.
 */
hash: string, };
