// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "../security/Category";
import type { Severity } from "../security/Severity";

/**
 * One row returned by `list_security_findings`. The shape pre-joins
 * the owning component's name and path so the UI doesn't have to
 * chase a second IPC call per row.
 */
export type FindingSummary = { id: string, componentId: string, componentName: string, componentPath: string, category: Category, pattern: string, severity: Severity, sourceLabel: string, redactedPreview: string, detectedAt: bigint, suppressed: boolean, };
