// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolHealthCount } from "./ToolHealthCount";

/**
 * Aggregate counts surfaced by `get_health_summary`.
 *
 * MVP keeps the structure flat - per-tool and per-kind counts live in
 * the same vector; the React side groups for display. Real MCP
 * probing is v1; for now every component reports `Unprobed` (the
 * `health` column on `component` is NULL).
 */
export type HealthSummary = { totalComponents: number, totalParseErrors: number, byToolKind: Array<ToolHealthCount>, };
