// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Strongly-typed IPC error returned by commands that need to discriminate
 * failure modes (rather than collapsing everything to a `String`). The
 * React layer pattern-matches on the `kind` discriminator to render
 * targeted messaging - "file too large", "id not found", etc.
 *
 * Phase 3.1 introduces this for `read_component_raw`. Older commands
 * still return `Result<_, String>`; they will migrate as they grow
 * failure-mode complexity.
 */
export type IpcError = { "kind": "notFound", id: string, } | { "kind": "payloadTooLarge", 
/**
 * Actual size in bytes.
 */
size: bigint, 
/**
 * Configured cap in bytes (5 MiB at the moment, matching the
 * parser).
 */
cap: bigint, } | { "kind": "io", message: string, } | { "kind": "invalidUtf8" } | { "kind": "index", message: string, };
