// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationError } from "../validator/ValidationError";

/**
 * Outcome of a `save_component` call.
 *
 * One of four shapes - the React layer pattern-matches on `kind`:
 *
 * * `Saved` - the file was written and re-indexed; the new content
 *   hash and mtime are returned so the editor can update its
 *   "original" snapshot for the next external-change check.
 * * `ExternalChange` - the on-disk hash diverged from the hash the
 *   editor opened the file with. The current bytes + hash are
 *   returned so the UI can render a diff banner with "Reload" /
 *   "Save anyway" choices.
 * * `ValidationFailed` - the new content parses but fails the
 *   per-tool schema. The errors are returned with JSON pointers so
 *   the form pane can highlight the offending fields. We do **not**
 *   write to disk in this case.
 * * `Forbidden` - a path-safety guard rejected the write
 *   (forbidden segment, escape outside the tool root, ...). The
 *   reason is human-readable.
 *
 * All variants are camelCase on the wire (`saved` /
 * `externalChange` / `validationFailed` / `forbidden`).
 */
export type SaveOutcome = { "kind": "saved", 
/**
 * New SHA-256 (hex) of the on-disk content.
 */
newHash: string, 
/**
 * Unix epoch seconds for the new file mtime.
 */
mtime: bigint, } | { "kind": "externalChange", 
/**
 * SHA-256 (hex) of the bytes currently on disk.
 */
currentHash: string, 
/**
 * Bytes currently on disk (UTF-8). Capped at the parser's
 * `MAX_PARSE_SIZE` for the same reason `read_component_raw`
 * is - the editor cannot meaningfully diff multi-MB blobs.
 */
currentContent: string, } | { "kind": "validationFailed", errors: Array<ValidationError>, } | { "kind": "forbidden", reason: string, };
