// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { Scope } from "../registry/Scope";
import type { ToolId } from "../registry/ToolId";

/**
 * Parameters for the FTS5-backed search.
 */
export type SearchQuery = { text: string, 
/**
 * Default 50; clamped to 200 server-side.
 */
limit: number | null, toolId: ToolId | null, kind: ComponentType | null, scope: Scope | null, };
