// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { Format } from "../registry/Format";
import type { Scope } from "../registry/Scope";
import type { ToolId } from "../registry/ToolId";

/**
 * One hit returned by `search`. Carries the matched-snippet from the
 * FTS5 `snippet()` aux function so the UI can render highlighted
 * excerpts without re-querying.
 */
export type SearchResult = { snippet: string, id: string, name: string, displayName: string | null, description: string | null, kind: ComponentType, tool: ToolId, scope: Scope, format: Format, path: string, size: bigint, mtime: bigint, hash: string, hasParseErrors: boolean, lastUsedAt: bigint | null, useCount: number, };
