// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "../security/Category";
import type { Severity } from "../security/Severity";

/**
 * Filter sent by the React UI to `list_security_findings`.
 *
 * All fields are optional; an empty filter returns the first
 * `limit` findings sorted by severity DESC, `detected_at` DESC.
 */
export type SecurityFilter = { 
/**
 * Restrict to a single component.
 */
componentId: string | null, severity: Severity | null, category: Category | null, 
/**
 * `Some(true)`  -> only suppressed findings;
 * `Some(false)` -> only active findings;
 * `None`        -> both. The Security view's "Suppressed" tab uses
 * the `Some(true)` form.
 */
suppressed: boolean | null, 
/**
 * Page size. Default 200; clamped to 1000 server-side.
 */
limit: number | null, 
/**
 * Offset into the result set (default 0).
 */
offset: number | null, };
