// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-category counts. `Default` keeps newly-added categories at zero
 * so a future variant doesn't break wire compat - the field shape can
 * grow without bumping a schema version.
 */
export type SecurityCategoryCounts = { secret: number, mcpPermission: number, };
