// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityCategoryCounts } from "./SecurityCategoryCounts";
import type { SeverityCounts } from "./SeverityCounts";

/**
 * Aggregate counts surfaced by `get_security_summary`.
 *
 * Drives the Sidebar Health group's "Security issues" entry +
 * the Security view header.
 */
export type SecuritySummary = { total: number, bySeverity: SeverityCounts, byCategory: SecurityCategoryCounts, suppressed: number, };
