// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-severity finding counts, used by the inventory shield badge to
 * pick the highest-severity colour without a second round-trip.
 */
export type SeverityCounts = { low: number, medium: number, high: number, critical: number, };
