// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "../registry/ComponentType";
import type { ToolId } from "../registry/ToolId";

/**
 * Per-(tool, kind) component count for the health summary view.
 */
export type ToolHealthCount = { tool: ToolId, kind: ComponentType, count: number, };
