// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse category for a backup-pass per-component failure.
 */
export type BackupErrorKind = "read" | "encrypt" | "write" | "keychainUnavailable" | "manifest";
