// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status payload for the `backup_status` IPC command. Frontend uses
 * this to populate the Settings -> Backup pane.
 */
export type BackupStatusReport = { 
/**
 * True iff the device public key is cached in `app_settings`.
 */
keyPresent: boolean, 
/**
 * Number of rows in `backup_manifest`.
 */
manifestCount: number, 
/**
 * Last `encrypted_at` across the manifest, or `None` if empty.
 */
lastBackupAt: bigint | null, 
/**
 * `backupAutoEnabled` setting (defaults to `true`).
 */
autoBackupEnabled: boolean, 
/**
 * Absolute path of the backup root, surfaced for the
 * "Storage: ~/.aseye-backup/ (4.2 MB)" line.
 */
backupDir: string, };
