// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupErrorEntry } from "./BackupErrorEntry";

/**
 * Outcome of a `backup_now` sweep.
 *
 * Per-component failures collect in `errors` but do NOT abort the
 * pass - the sweep continues so one bad row does not lose another
 * component's chance at a fresh blob.
 */
export type BackupReport = { 
/**
 * Total number of indexed components considered.
 */
total: number, 
/**
 * Components encrypted + written this pass (insert or refresh).
 */
encrypted: number, 
/**
 * Components whose plaintext hash matched the manifest - no work
 * performed.
 */
skippedUnchanged: number, 
/**
 * Per-component failures. Each entry carries enough context for
 * the UI to surface a row-level error toast without a follow-up
 * IPC call.
 */
errors: Array<BackupErrorEntry>, 
/**
 * Wall-clock duration of the pass in milliseconds.
 */
elapsedMs: bigint, };
