// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupErrorKind } from "./BackupErrorKind";

/**
 * One row in `BackupReport.errors`.
 */
export type BackupErrorEntry = { componentId: string, kind: BackupErrorKind, message: string, };
