// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreErrorEntry } from "./RestoreErrorEntry";

/**
 * Outcome of a `restore_now` sweep.
 */
export type RestoreReport = { 
/**
 * Total entries in the manifest considered.
 */
total: number, 
/**
 * Files actually restored to disk.
 */
restored: number, 
/**
 * Files skipped because the local copy was newer than the backup
 * (`encrypted_at`).
 */
skippedLocalNewer: number, 
/**
 * Per-entry failures.
 */
errors: Array<RestoreErrorEntry>, 
/**
 * Wall-clock duration of the pass in milliseconds.
 */
elapsedMs: bigint, 
/**
 * Whether this was a dry-run (no writes performed).
 */
dryRun: boolean, };
