// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestoreErrorKind } from "./RestoreErrorKind";

/**
 * One row in `RestoreReport.errors`.
 */
export type RestoreErrorEntry = { componentId: string, kind: RestoreErrorKind, message: string, };
