// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse category for a restore-pass per-entry failure.
 */
export type RestoreErrorKind = "read" | "decrypt" | "write" | "keychainUnavailable" | "componentMissing" | "pathUnreachable";
