// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerifyErrorEntry } from "./VerifyErrorEntry";

/**
 * Outcome of a `backup_verify` sweep. Walks every manifest row,
 * re-reads the blob, hashes the ciphertext (compared against
 * `blob_hash`), decrypts it, and hashes the plaintext (compared
 * against `plaintext_hash`). Any mismatch surfaces as an error
 * entry but does not abort the pass.
 */
export type VerifyReport = { 
/**
 * Total entries in the manifest considered.
 */
total: number, 
/**
 * Entries that passed both the ciphertext-hash and plaintext-hash
 * checks - the all-clear count.
 */
verified: number, 
/**
 * Per-entry failures. Each carries enough context for the UI to
 * surface row-level detail without a follow-up IPC call.
 */
errors: Array<VerifyErrorEntry>, 
/**
 * Wall-clock duration of the pass in milliseconds.
 */
elapsedMs: bigint, };
