// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerifyErrorKind } from "./VerifyErrorKind";

/**
 * One row in `VerifyReport.errors`.
 */
export type VerifyErrorEntry = { componentId: string, kind: VerifyErrorKind, message: string, };
