// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse category for a verify-pass per-entry failure.
 */
export type VerifyErrorKind = "read" | "blobHashMismatch" | "decrypt" | "plaintextHashMismatch" | "keychainUnavailable";
