// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryRecommendation } from "./MemoryRecommendation";

/**
 * Outcome of the `analyze_memory` action.
 */
export type MemoryAnalysisReport = { projectPath: string, memoryPath: string, sizeBytes: bigint, tokensEst: bigint, recommendations: Array<MemoryRecommendation>, elapsedMs: bigint, };
