// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One memory file inside a project. Multiple are possible when a
 * project is used by more than one tool.
 */
export type MemoryFileSummary = { 
/**
 * Filename only (e.g. `"CLAUDE.md"`).
 */
basename: string, 
/**
 * Absolute path to the file.
 */
path: string, size: bigint, 
/**
 * Last-modified time as unix seconds.
 */
mtime: bigint, };
