// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryRecommendationKind } from "./MemoryRecommendationKind";

/**
 * One row in `MemoryAnalysisReport.recommendations`.
 */
export type MemoryRecommendation = { kind: MemoryRecommendationKind, message: string, estimatedSavingsBytes: bigint, 
/**
 * 1-indexed `(start, end_inclusive)` line range for "open in
 * editor at line N". `None` when the heuristic does not point
 * at a specific span (e.g. `Oversized` applies to the whole
 * file).
 */
lineRange: [number, number] | null, };
