// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryFileSummary } from "./MemoryFileSummary";

/**
 * One project surfaced in the Projects view. A "project" is the
 * parent directory of an indexed memory component (CLAUDE.md /
 * AGENTS.md / GEMINI.md).
 */
export type ProjectSummary = { 
/**
 * Absolute path to the project root.
 */
projectPath: string, 
/**
 * Human-readable label - last 1-2 path segments, e.g.
 * `"Development/projectfinish"`.
 */
displayName: string, 
/**
 * Every indexed memory file at the project root. There is
 * usually one (CLAUDE.md) but a project can have multiple
 * (CLAUDE.md + AGENTS.md if it's used by both Claude and Codex).
 */
memoryFiles: Array<MemoryFileSummary>, 
/**
 * Size in bytes of the primary memory file. Preference order
 * CLAUDE.md > AGENTS.md > GEMINI.md.
 */
primaryMemoryPath: string, primaryMemorySize: bigint, 
/**
 * Token estimate for the primary memory file (size / 4 heuristic,
 * matching the inventory size chip).
 */
primaryMemoryTokensEst: bigint, 
/**
 * True when the primary memory file is over the spec's 8 KiB
 * "oversized" threshold. Drives the warning glyph in the UI.
 */
isOversized: boolean, 
/**
 * True iff the project root contains a `.git/` directory. Drives
 * whether the worktree audit action is enabled.
 */
hasGit: boolean, };
