// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReorganizeErrorKind } from "./ReorganizeErrorKind";

export type ReorganizeError = { path: string, kind: ReorganizeErrorKind, message: string, };
