// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkRewrite } from "./LinkRewrite";
import type { ReorganizeError } from "./ReorganizeError";
import type { ReorganizeMove } from "./ReorganizeMove";

export type ReorganizeReport = { projectPath: string, dryRun: boolean, moves: Array<ReorganizeMove>, linkRewrites: Array<LinkRewrite>, errors: Array<ReorganizeError>, elapsedMs: bigint, 
/**
 * True iff the link-rewrite walk hit the entry / time cap.
 */
walkIncomplete: boolean, };
