// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeEntry } from "./WorktreeEntry";

export type WorktreeReport = { projectPath: string, worktrees: Array<WorktreeEntry>, totalDiskUsageBytes: bigint, elapsedMs: bigint, };
