// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeEntry = { 
/**
 * Absolute path to the worktree.
 */
path: string, 
/**
 * Branch checked out, when the worktree is on a branch (vs.
 * detached HEAD).
 */
branch: string | null, 
/**
 * Commit SHA the worktree's HEAD points at.
 */
head: string, 
/**
 * True iff `git worktree list --porcelain` reported `locked`.
 */
locked: boolean, 
/**
 * Lock reason string when `locked = true`.
 */
lockReason: string | null, 
/**
 * Mtime of the worktree directory (the most recent file
 * modification we could observe). Drives the "age" hint in the
 * UI. Unix seconds; 0 when unavailable.
 */
mtimeUnix: bigint, 
/**
 * Recursive disk usage in bytes. May be 0 when the walk failed
 * outright (which the UI surfaces as `(unknown size)`).
 */
diskUsageBytes: bigint, 
/**
 * True iff the disk-usage walk hit the entry / time cap before
 * finishing. The UI shows a "incomplete" hint so the user knows
 * the number is a lower bound.
 */
incomplete: boolean, 
/**
 * True iff this is the main worktree (the project root itself).
 * `git worktree list` always emits the main first.
 */
isMain: boolean, };
