// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of the `parse_errors` entry written by the upsert layer.
 *
 * Phase 3.2 - the existing `parse_errors` column now carries either a
 * hard parse failure or a validation failure. The on-wire shape is a
 * JSON object with `kind` set to one of these strings so the UI can
 * render different badges. Existing entries (pre-3.2) are pure
 * `{"message": "..."}` objects without a `kind` field; the UI treats
 * those as `Parse` for back-compat.
 */
export type ParseErrorKind = "parse" | "validation";
