// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationError } from "./ValidationError";
import type { ValidationWarning } from "./ValidationWarning";

/**
 * Outcome of validating a parsed component against its bundled schema.
 *
 * `ok` is `true` when there are zero validation errors. Warnings do
 * not affect `ok` - the user can still save a component with unknown
 * fields, but the UI surfaces them so the user can decide whether to
 * remove them.
 */
export type ValidationOutcome = { 
/**
 * `true` when `errors` is empty.
 */
ok: boolean, 
/**
 * Hard validation failures (missing required fields, wrong type,
 * failed constraint). The save path uses these to gate "save
 * anyway" prompts.
 */
errors: Array<ValidationError>, 
/**
 * Soft warnings (unknown fields the schema doesn't list under
 * `properties`). Surfaced in the UI as informational badges; never
 * block a save.
 */
warnings: Array<ValidationWarning>, };
