// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator for the kinds of warning the validator emits.
 *
 * New variants are additive; existing ones are stable. The TS binding
 * renders each as a camelCase string for UI pattern-matching.
 */
export type ValidationWarningKind = "unknownField";
