// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single validation error: where it occurred (JSON pointer), what
 * was wrong (human-readable message), and which schema keyword was
 * violated (`required`, `type`, `enum`, `pattern`, ...).
 */
export type ValidationError = { 
/**
 * JSON pointer (RFC 6901) to the offending value, e.g.
 * `/frontmatter/name` or `/mcpServers/github/command`. Empty
 * string for root-level violations (e.g. `required` errors that
 * reference a missing field at the root).
 */
path: string, 
/**
 * Human-readable description from the underlying validator.
 */
message: string, 
/**
 * The JSON Schema keyword that triggered the failure. Stable
 * camelCase strings: `required`, `type`, `enum`, `anyOf`,
 * `oneOf`, `pattern`, `minLength`, `maxLength`, `format`, ...
 */
schemaKeyword: string, };
