// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationWarningKind } from "./ValidationWarningKind";

/**
 * A non-blocking warning emitted alongside validation. Currently the
 * only kind is [`ValidationWarningKind::UnknownField`] but the type
 * is intentionally extensible so Phase 7.3 can add lint-level
 * warnings without a wire-format change.
 */
export type ValidationWarning = { kind: ValidationWarningKind, 
/**
 * JSON pointer to the field the warning references.
 */
path: string, message: string, };
