// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanReport } from "./ScanReport";
import type { UpsertKind } from "../index/UpsertOutcome";

/**
 * Event emitted by the pipeline after a successful classify + index
 * step.
 *
 * Serialised as a tagged union with `event` as the discriminator so it
 * doesn't collide with the `kind: UpsertKind` field on
 * `ComponentUpserted`. The TS bindings (and the React side via
 * `pipeline-event` Tauri events) use the same shape.
 */
export type PipelineEvent = { "event": "componentUpserted", id: string, kind: UpsertKind, } | { "event": "componentDeleted", id: string, } | { "event": "parseError", id: string, path: string, } | { "event": "scanCompleted", report: ScanReport, };
