// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a `Pipeline::full_scan` run. Returned synchronously from
 * the `start_full_scan` command and also emitted as a
 * `PipelineEvent::ScanCompleted` so subscribers can refresh totals.
 */
export type ScanReport = { 
/**
 * Number of tools the scan walked (i.e. detected tools).
 */
toolsScanned: number, 
/**
 * Number of components seen during the walk (one per file match).
 */
componentsSeen: number, 
/**
 * Number of components inserted for the first time during this
 * scan.
 */
componentsInserted: number, 
/**
 * Number of components whose row was updated.
 */
componentsUpdated: number, 
/**
 * Number of components whose hash matched the existing row.
 */
componentsUnchanged: number, 
/**
 * Number of files that failed to parse but still recorded a row.
 */
parseErrors: number, };
