//! IPC wire types.
//!
//! Every type that crosses the Tauri IPC boundary derives `TS` so the
//! TypeScript bindings under `bindings/ipc/` are generated by ts-rs
//! rather than hand-written. The serde rename rules match the rest of
//! the crate (`camelCase` on the wire).

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::registry::types::{ComponentType, Format, Scope, ToolId};

/// Filter sent by the React UI to `list_components`.
///
/// All fields are optional; an empty filter returns the first
/// `limit` components ordered by `mtime DESC`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentFilter.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentFilter {
    pub tool_id: Option<ToolId>,
    pub kind: Option<ComponentType>,
    pub scope: Option<Scope>,
    /// Substring match against `name` and `description`. Implemented
    /// via `LIKE` so it does NOT use FTS - that is the dedicated
    /// `search` command's job.
    pub query: Option<String>,
    /// Filter by user-applied tag.
    pub tag: Option<String>,
    /// Page size. Default 200; clamped to 1000 server-side.
    pub limit: Option<u32>,
    /// Offset into the result set (default 0).
    pub offset: Option<u32>,
}

/// One entry in a `list_components` result.
///
/// Lightweight by design: full parsed content lives behind
/// `get_component`. `ComponentSummary` is what populates Inventory
/// rows, sidebar facets, and the Map view nodes.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentSummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentSummary {
    pub id: String,
    pub name: String,
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub kind: ComponentType,
    pub tool: ToolId,
    pub scope: Scope,
    pub format: Format,
    pub path: String,
    pub size: u64,
    pub mtime: i64,
    pub hash: String,
    pub has_parse_errors: bool,
    pub last_used_at: Option<i64>,
    pub use_count: u32,
}

/// Full row returned by `get_component`.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentDetail.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentDetail {
    #[serde(flatten)]
    pub summary: ComponentSummary,
    /// JSON-encoded parsed content. Schema depends on `format`.
    pub parsed_json: Option<String>,
    /// JSON-encoded parse error metadata, when `has_parse_errors`.
    pub parse_errors: Option<String>,
    pub origin: String,
    pub plugin_id: Option<String>,
}

/// Parameters for the FTS5-backed search.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SearchQuery.ts")]
#[ts(rename_all = "camelCase")]
pub struct SearchQuery {
    pub text: String,
    /// Default 50; clamped to 200 server-side.
    pub limit: Option<u32>,
    pub tool_id: Option<ToolId>,
    pub kind: Option<ComponentType>,
    pub scope: Option<Scope>,
}

/// One hit returned by `search`. Carries the matched-snippet from the
/// FTS5 `snippet()` aux function so the UI can render highlighted
/// excerpts without re-querying.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SearchResult.ts")]
#[ts(rename_all = "camelCase")]
pub struct SearchResult {
    #[serde(flatten)]
    pub summary: ComponentSummary,
    pub snippet: String,
}

/// Per-(tool, kind) component count for the health summary view.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ToolHealthCount.ts")]
#[ts(rename_all = "camelCase")]
pub struct ToolHealthCount {
    pub tool: ToolId,
    pub kind: ComponentType,
    pub count: u32,
}

/// Aggregate counts surfaced by `get_health_summary`.
///
/// MVP keeps the structure flat - per-tool and per-kind counts live in
/// the same vector; the React side groups for display. Real MCP
/// probing is v1; for now every component reports `Unprobed` (the
/// `health` column on `component` is NULL).
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/HealthSummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct HealthSummary {
    pub total_components: u32,
    pub total_parse_errors: u32,
    pub by_tool_kind: Vec<ToolHealthCount>,
}
