//! IPC wire types.
//!
//! Every type that crosses the Tauri IPC boundary derives `TS` so the
//! TypeScript bindings under `bindings/ipc/` are generated by ts-rs
//! rather than hand-written. The serde rename rules match the rest of
//! the crate (`camelCase` on the wire).

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::registry::types::{ComponentType, Format, Scope, ToolId};
use crate::security::{Category as SecurityCategory, Severity};

/// Strongly-typed IPC error returned by commands that need to discriminate
/// failure modes (rather than collapsing everything to a `String`). The
/// React layer pattern-matches on the `kind` discriminator to render
/// targeted messaging - "file too large", "id not found", etc.
///
/// Phase 3.1 introduces this for `read_component_raw`. Older commands
/// still return `Result<_, String>`; they will migrate as they grow
/// failure-mode complexity.
#[derive(Debug, thiserror::Error, Serialize, Deserialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/IpcError.ts")]
#[ts(rename_all = "camelCase")]
pub enum IpcError {
    /// The supplied component id has no row in the index.
    #[error("component {id} was not found")]
    NotFound {
        #[serde(rename = "id")]
        id: String,
    },
    /// The on-disk file exceeds the parser cap; the editor refuses to
    /// load multi-megabyte text into Monaco.
    #[error("payload size {size} exceeds cap {cap}")]
    PayloadTooLarge {
        /// Actual size in bytes.
        size: u64,
        /// Configured cap in bytes (5 MiB at the moment, matching the
        /// parser).
        cap: u64,
    },
    /// Reading the file off disk failed (permission denied, EIO, ...).
    /// The message is rendered verbatim - we don't expose internal paths
    /// here because the caller already knows the path it requested.
    #[error("io error: {message}")]
    Io { message: String },
    /// File contents were not valid UTF-8. Monaco cannot edit binary
    /// content; the user is shown a friendlier error than `from_utf8`.
    #[error("file is not valid UTF-8")]
    InvalidUtf8,
    /// Underlying `SQLite` read failed. Surfaced as a fallback when the
    /// index is in a bad state.
    #[error("index error: {message}")]
    Index { message: String },
}

/// Filter sent by the React UI to `list_components`.
///
/// All fields are optional; an empty filter returns the first
/// `limit` components ordered by `mtime DESC`.
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentFilter.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentFilter {
    pub tool_id: Option<ToolId>,
    pub kind: Option<ComponentType>,
    pub scope: Option<Scope>,
    /// Substring match against `name` and `description`. Implemented
    /// via `LIKE` so it does NOT use FTS - that is the dedicated
    /// `search` command's job.
    pub query: Option<String>,
    /// Filter by user-applied tag.
    pub tag: Option<String>,
    /// Page size. Default 200; clamped to 1000 server-side.
    pub limit: Option<u32>,
    /// Offset into the result set (default 0).
    pub offset: Option<u32>,
}

/// One entry in a `list_components` result.
///
/// Lightweight by design: full parsed content lives behind
/// `get_component`. `ComponentSummary` is what populates Inventory
/// rows, sidebar facets, and the Map view nodes.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentSummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentSummary {
    pub id: String,
    pub name: String,
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub kind: ComponentType,
    pub tool: ToolId,
    pub scope: Scope,
    pub format: Format,
    pub path: String,
    pub size: u64,
    pub mtime: i64,
    pub hash: String,
    pub has_parse_errors: bool,
    pub last_used_at: Option<i64>,
    pub use_count: u32,
}

/// Full row returned by `get_component`.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentDetail.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentDetail {
    #[serde(flatten)]
    pub summary: ComponentSummary,
    /// JSON-encoded parsed content. Schema depends on `format`.
    pub parsed_json: Option<String>,
    /// JSON-encoded parse error metadata, when `has_parse_errors`.
    pub parse_errors: Option<String>,
    pub origin: String,
    pub plugin_id: Option<String>,
}

/// Parameters for the FTS5-backed search.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SearchQuery.ts")]
#[ts(rename_all = "camelCase")]
pub struct SearchQuery {
    pub text: String,
    /// Default 50; clamped to 200 server-side.
    pub limit: Option<u32>,
    pub tool_id: Option<ToolId>,
    pub kind: Option<ComponentType>,
    pub scope: Option<Scope>,
}

/// One hit returned by `search`. Carries the matched-snippet from the
/// FTS5 `snippet()` aux function so the UI can render highlighted
/// excerpts without re-querying.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SearchResult.ts")]
#[ts(rename_all = "camelCase")]
pub struct SearchResult {
    #[serde(flatten)]
    pub summary: ComponentSummary,
    pub snippet: String,
}

/// Per-(tool, kind) component count for the health summary view.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ToolHealthCount.ts")]
#[ts(rename_all = "camelCase")]
pub struct ToolHealthCount {
    pub tool: ToolId,
    pub kind: ComponentType,
    pub count: u32,
}

/// Aggregate counts surfaced by `get_health_summary`.
///
/// MVP keeps the structure flat - per-tool and per-kind counts live in
/// the same vector; the React side groups for display. Real MCP
/// probing is v1; for now every component reports `Unprobed` (the
/// `health` column on `component` is NULL).
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/HealthSummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct HealthSummary {
    pub total_components: u32,
    pub total_parse_errors: u32,
    pub by_tool_kind: Vec<ToolHealthCount>,
}

// ─── Phase 7.3 - Security view IPC types ────────────────────────────────
//
// These types are scaffolded ahead of the Phase 7.3 commands. They are
// not yet referenced by any `#[tauri::command]` handler; the
// `#[allow(dead_code)]` keeps clippy happy until those handlers land.

/// Filter sent by the React UI to `list_security_findings`.
///
/// All fields are optional; an empty filter returns the first
/// `limit` findings sorted by severity DESC, `detected_at` DESC.
#[allow(dead_code)]
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SecurityFilter.ts")]
#[ts(rename_all = "camelCase")]
pub struct SecurityFilter {
    /// Restrict to a single component.
    pub component_id: Option<String>,
    pub severity: Option<Severity>,
    pub category: Option<SecurityCategory>,
    /// `Some(true)`  -> only suppressed findings;
    /// `Some(false)` -> only active findings;
    /// `None`        -> both. The Security view's "Suppressed" tab uses
    /// the `Some(true)` form.
    pub suppressed: Option<bool>,
    /// Page size. Default 200; clamped to 1000 server-side.
    pub limit: Option<u32>,
    /// Offset into the result set (default 0).
    pub offset: Option<u32>,
}

/// One row returned by `list_security_findings`. The shape pre-joins
/// the owning component's name and path so the UI doesn't have to
/// chase a second IPC call per row.
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/FindingSummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct FindingSummary {
    pub id: String,
    pub component_id: String,
    pub component_name: String,
    pub component_path: String,
    pub category: SecurityCategory,
    pub pattern: String,
    pub severity: Severity,
    pub source_label: String,
    pub redacted_preview: String,
    pub detected_at: i64,
    pub suppressed: bool,
}

/// Per-severity finding counts, used by the inventory shield badge to
/// pick the highest-severity colour without a second round-trip.
#[allow(dead_code)]
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SeverityCounts.ts")]
#[ts(rename_all = "camelCase")]
pub struct SeverityCounts {
    pub low: u32,
    pub medium: u32,
    pub high: u32,
    pub critical: u32,
}

/// One row returned by `get_findings_count_per_component`.
#[allow(dead_code)]
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/ComponentFindingsCount.ts")]
#[ts(rename_all = "camelCase")]
pub struct ComponentFindingsCount {
    pub component_id: String,
    pub total: u32,
    pub by_severity: SeverityCounts,
}

/// Per-category counts. `Default` keeps newly-added categories at zero
/// so a future variant doesn't break wire compat - the field shape can
/// grow without bumping a schema version.
#[allow(dead_code)]
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SecurityCategoryCounts.ts")]
#[ts(rename_all = "camelCase")]
pub struct SecurityCategoryCounts {
    pub secret: u32,
    pub mcp_permission: u32,
}

/// Aggregate counts surfaced by `get_security_summary`.
///
/// Drives the Sidebar Health group's "Security issues" entry +
/// the Security view header.
#[allow(dead_code)]
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export, export_to = "../bindings/ipc/SecuritySummary.ts")]
#[ts(rename_all = "camelCase")]
pub struct SecuritySummary {
    pub total: u32,
    pub by_severity: SeverityCounts,
    pub by_category: SecurityCategoryCounts,
    pub suppressed: u32,
}
