// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unified component taxonomy from `docs/03-component-model.md` (the
 * 16 first-class component types). Serialised as camelCase strings so the
 * wire format is the JS-native shape.
 */
export type ComponentType = "tool" | "settings" | "memory" | "rule" | "skill" | "command" | "agent" | "mcp" | "hook" | "plugin" | "marketplace" | "session" | "task" | "outputStyle" | "statusline" | "permission";
