// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentType } from "./ComponentType";
import type { Format } from "./Format";
import type { Scope } from "./Scope";

/**
 * Description of where to look for a particular component type within a tool.
 *
 * `path_pattern` may contain `~/` (HOME) and glob wildcards (`*`, `**`). When
 * `is_folder` is true, the pattern resolves to a directory (typically the
 * folder that contains a `SKILL.md`). When `key_path` is set, the component
 * is embedded inside the file at `path_pattern` under that JSON / TOML key
 * (e.g. Claude Code's `mcpServers` lives inside `~/.claude.json`).
 */
export type ComponentRoot = { componentType: ComponentType, pathPattern: string, format: Format, 
/**
 * Filename flavour the parser should preserve on save (`CLAUDE.md`,
 * `AGENTS.md`, `GEMINI.md`, ...). Optional because most components are
 * flavour-less.
 */
flavour: string | null, scope: Scope, 
/**
 * True when the component identity is the folder, not a single file
 * (e.g. skill folders).
 */
isFolder: boolean, 
/**
 * Dot-separated key path inside the container file when the component
 * is embedded (e.g. `"mcpServers"` inside `~/.claude.json`).
 */
keyPath: string | null, };
