// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolId } from "./ToolId";

/**
 * Result of probing the host system for a particular tool.
 */
export type DetectedTool = { id: ToolId, displayName: string, detected: boolean, 
/**
 * Absolute path of the matched binary on `PATH`, when one was found.
 */
binary: string | null, 
/**
 * Trimmed stdout of the version command, when it ran successfully.
 */
version: string | null, 
/**
 * Subset of `ToolDescriptor::detection_paths` whose targets exist
 * on the local filesystem (with `~/` expanded).
 */
existingRootPaths: Array<string>, };
