// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On-disk format for a component or its container file.
 */
export type Format = "json" | "toml" | "yaml" | "markdown" | "markdownfrontmatter" | "mdc" | "jsonl" | "sqlite" | "binary";
