// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a component lives in the layered scope hierarchy.
 */
export type Scope = "user" | "project" | "enterprise" | "plugin";
