// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentRoot } from "./ComponentRoot";
import type { ToolId } from "./ToolId";

/**
 * Static description of a host tool we know how to detect and inspect.
 */
export type ToolDescriptor = { id: ToolId, displayName: string, 
/**
 * Names to look for on the user's `PATH` when probing for a CLI binary.
 */
binaryNames: Array<string>, 
/**
 * Filesystem paths whose existence implies the tool is installed
 * (HOME-relative paths use a leading `~/`).
 */
detectionPaths: Array<string>, 
/**
 * Command to run to capture the tool version. The first whitespace
 * token is the executable; subsequent tokens are passed as arguments.
 */
versionCommand: string | null, 
/**
 * Per-component on-disk locations for this tool.
 */
componentRoots: Array<ComponentRoot>, 
/**
 * Paths the watcher should subscribe to for live updates (Phase 1.3).
 */
watchPaths: Array<string>, };
