// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier for a host tool we know about.
 *
 * Serialised as kebab-case strings (`claude-code`, `codex`, `cursor`,
 * `antigravity`) so the wire format is stable across Rust and TS.
 */
export type ToolId = "claude-code" | "codex" | "cursor" | "antigravity";
