// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "../registry/Format";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ParseWarning } from "./ParseWarning";

/**
 * Output of parsing a single component file.
 *
 * Field semantics depend on the source format:
 * * `frontmatter` - YAML frontmatter for Markdown / MDC; `None` for
 *   pure-data formats (JSON / TOML / YAML).
 * * `body` - Markdown / doc body text; `None` for pure-data formats.
 * * `structured` - the full parsed value for JSON / TOML / YAML;
 *   `None` for Markdown without frontmatter.
 * * `raw` - verbatim bytes off disk, kept for round-trip serialisation.
 * * `hash` - SHA-256 hex of `raw`.
 * * `format` - the source format, copied through from the caller.
 * * `size` - `raw.len()` as `u64` for ergonomic comparison with
 *   `std::fs::Metadata::len`.
 * * `warnings` - non-fatal warnings (`UnclosedFrontmatter`,
 *   `MultipleYamlDocuments`, ...).
 */
export type ParsedComponent = { frontmatter: JsonValue | null, body: string | null, structured: JsonValue | null, raw: Array<number>, hash: string, format: Format, size: bigint, warnings: Array<ParseWarning>, };
