// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseWarningKind } from "./ParseWarningKind";

/**
 * A non-fatal warning produced while parsing a file.
 */
export type ParseWarning = { kind: ParseWarningKind, message: string, 
/**
 * 1-based line number when known. `None` when the warning is
 * document-wide rather than positional.
 */
line: number | null, };
