// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator for the kinds of warnings the parser layer emits.
 *
 * Kept small and deliberately stable - each variant becomes a string
 * in the TS binding the UI may pattern-match on.
 */
export type ParseWarningKind = "multipleYamlDocuments" | "unclosedFrontmatter" | "sizeExceeded";
