// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of an `upsert_component` call.
 *
 * Distinguishes "we wrote new data" from "the file content is identical
 * to what we already had", so the watcher pipeline can short-circuit
 * downstream work (relation recompute, broadcast emission) on no-op
 * modifications.
 */
export type UpsertKind = "inserted" | "updated" | "unchanged";
