// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpsertKind } from "./UpsertOutcome";

/**
 * Result returned from a successful upsert.
 */
export type UpsertOutcome = { id: string, kind: UpsertKind, hadParseError: boolean, };
