//! Index data wipers.
//!
//! Helpers backing the Settings -> Index "rebuild" button (audit issue
//! #5):
//!
//! * [`wipe_index_data`] - drop every row from the indexed-content
//!   tables (`component`, `component_fts`, `relation`, `tag`, `pin`,
//!   `note`, `health_probe`, `usage_event`, `security_finding`,
//!   `security_finding_suppression`, `token_usage`,
//!   `usage_session_watermark`). Schema and `app_settings` are kept so
//!   the next scan repopulates with the same configuration.
//!
//! The wipe runs inside a single transaction so a partial failure
//! never leaves the index in a half-cleared state. Foreign-key cascades
//! mean we only need to delete from the parent tables, but we delete
//! from every content table explicitly so the wipe is auditable from
//! the SQL side.

use rusqlite::Connection;

use super::error::Result;
use super::IndexHandle;

/// Tables that hold *indexed content* - everything that can be
/// regenerated by re-running a full scan.
///
/// Order matters only for readability: the foreign-key declarations
/// already cascade `component` -> `component_file` / `security_finding`,
/// so deleting `component` would clear them, but listing every table
/// explicitly keeps the wipe auditable from the SQL side and protects
/// us if a future schema migration drops the cascade.
const CONTENT_TABLES: &[&str] = &[
    "component_fts",
    "component_file",
    "component",
    "relation",
    "tag",
    "pin",
    "note",
    "health_probe",
    "usage_event",
    "security_finding",
    "security_finding_suppression",
    "token_usage",
    "usage_session_watermark",
];

/// Wipe every indexed-content row but keep user preferences.
///
/// Called by the `rebuild_index` IPC. The next full scan repopulates
/// `component`, the FTS index, and the security findings using the
/// same `app_settings.projectMemoryRoots`, `excludedToolIds`, and any
/// other persisted preferences.
pub fn wipe_index_data(handle: &IndexHandle) -> Result<()> {
    handle.write(|conn| {
        delete_from_tables(conn, CONTENT_TABLES)?;
        Ok(())
    })
}

/// Delete every row from each table inside a single transaction.
///
/// We drive the transaction by hand rather than via `conn.transaction()`
/// because the surrounding closure is `FnOnce(&Connection)` (the write
/// helper takes a shared reference); the explicit BEGIN/COMMIT achieves
/// the same atomicity without needing a `&mut Connection`. A failure
/// rolls back via the bare `ROLLBACK` on the error branch.
fn delete_from_tables(conn: &Connection, tables: &[&str]) -> Result<()> {
    conn.execute("BEGIN", [])?;
    for table in tables {
        // Each table name is a compile-time `&'static str` from the
        // module-private constants, so format-injection is impossible
        // here. SQLite does not allow a parameter binding for table
        // identifiers.
        let sql = format!("DELETE FROM {table}");
        if let Err(err) = conn.execute(&sql, []) {
            // Best-effort rollback; if the rollback itself errors we
            // still surface the original error to the caller.
            let _ = conn.execute("ROLLBACK", []);
            return Err(err.into());
        }
    }
    conn.execute("COMMIT", [])?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::params;

    fn count_rows(handle: &IndexHandle, table: &str) -> i64 {
        handle
            .read(|conn| {
                conn.query_row(&format!("SELECT COUNT(*) FROM {table}"), [], |row| {
                    row.get::<_, i64>(0)
                })
                .map_err(Into::into)
            })
            .expect("count")
    }

    /// Insert a minimal component row plus a downstream finding so the
    /// wipe has something to delete. We bypass `upsert_component` here
    /// because the tests only need raw rows on disk - the real
    /// pipeline path is exercised in scan tests elsewhere.
    fn seed_minimal_state(handle: &IndexHandle) {
        handle
            .write(|conn| {
                conn.execute(
                    "INSERT INTO component (id, type, tool, scope, origin, name, path, format, hash, updated_at)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
                    params![
                        "aseye://t/wipe-c1",
                        "skill",
                        "claude-code",
                        "user",
                        "fs",
                        "wipe-c1",
                        "/tmp/wipe-c1",
                        "markdown",
                        "deadbeef",
                        0_i64,
                    ],
                )?;
                conn.execute(
                    "INSERT INTO component_fts (id, name, description, body) VALUES (?1, ?2, ?3, ?4)",
                    params!["aseye://t/wipe-c1", "wipe-c1", "", ""],
                )?;
                conn.execute(
                    "INSERT INTO security_finding
                     (id, component_id, category, pattern, severity, file_path, source_label, redacted_preview, detected_at, suppressed)
                     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)",
                    params![
                        "f-1",
                        "aseye://t/wipe-c1",
                        "secret",
                        "anthropic-key",
                        "critical",
                        "/tmp/wipe-c1",
                        "preview",
                        "***",
                        0_i64,
                        0_i64,
                    ],
                )?;
                conn.execute(
                    "INSERT INTO app_settings (key, value) VALUES (?1, ?2)",
                    params!["projectMemoryRoots", r#"["~/Code"]"#],
                )?;
                Ok(())
            })
            .expect("seed");
    }

    #[test]
    fn wipe_index_data_drops_content_but_keeps_settings() {
        let handle = IndexHandle::open_in_memory().expect("open");
        seed_minimal_state(&handle);

        assert_eq!(count_rows(&handle, "component"), 1);
        assert_eq!(count_rows(&handle, "security_finding"), 1);
        assert_eq!(count_rows(&handle, "app_settings"), 1);

        wipe_index_data(&handle).expect("wipe");

        assert_eq!(count_rows(&handle, "component"), 0);
        assert_eq!(count_rows(&handle, "security_finding"), 0);
        // Settings preserved across rebuild so the next scan reuses
        // the user's project-memory-roots / excludedToolIds choices.
        assert_eq!(count_rows(&handle, "app_settings"), 1);
    }

    /// Re-running the wipe on an already-empty database must succeed
    /// (idempotency). The IPC layer relies on this: a user clicking
    /// "rebuild" twice in quick succession should not surface an error
    /// on the second call.
    #[test]
    fn wipe_index_data_is_idempotent() {
        let handle = IndexHandle::open_in_memory().expect("open");
        wipe_index_data(&handle).expect("first wipe");
        wipe_index_data(&handle).expect("second wipe");
        assert_eq!(count_rows(&handle, "component"), 0);
    }

    /// FTS5 virtual table content must be cleared by the wipe so a
    /// re-scan does not reload search hits against stale rows.
    #[test]
    fn wipe_index_data_clears_fts_index() {
        let handle = IndexHandle::open_in_memory().expect("open");
        seed_minimal_state(&handle);
        assert_eq!(count_rows(&handle, "component_fts"), 1);
        wipe_index_data(&handle).expect("wipe");
        assert_eq!(count_rows(&handle, "component_fts"), 0);
    }
}
