// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update channel preference. The release pipeline publishes
 * `latest-stable.json` and `latest-beta.json` to GitHub Releases; this
 * enum picks which one to consult.
 */
export type UpdateChannel = "stable" | "beta";
