// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors surfaced to the frontend. Variants are deliberately narrow
 * so the UI can decide between "show an inline message" (e.g.
 * `Network`) and "log + bail silently" (e.g. `MissingEndpoint`).
 */
export type UpdateError = { "kind": "plugin", "message": string } | { "kind": "missingEndpoint" } | { "kind": "noConfigDir" } | { "kind": "settingsIo", "message": string };
