// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateChannel } from "./UpdateChannel";

/**
 * Payload returned from `check_for_update` and broadcast as the
 * `update-available` Tauri event when the daily poll finds a newer
 * version.
 */
export type UpdateAvailable = { 
/**
 * Newer version announced by the manifest.
 */
version: string, 
/**
 * Currently-installed version (from `tauri.conf.json -> version`).
 */
currentVersion: string, 
/**
 * Optional release notes body.
 */
notes: string | null, 
/**
 * Optional RFC3339-ish publish timestamp. Plugin parses
 * `time::OffsetDateTime`; we render it via `Display` to avoid a
 * direct dep on `time`.
 */
pubDate: string | null, 
/**
 * Channel that produced this update (matches the preference at
 * the time of the check).
 */
channel: UpdateChannel, };
