// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit category. Phase 7.1 ships `Secret`; Phase 7.2 adds
 * `McpPermission`. Phase 7.3 will add `Hook` / `Plugin` /
 * `PathTraversal` / `SensitiveDir` / `License`. The variant is
 * open-ended so future work can extend without breaking serialised
 * rows.
 */
export type Category = "secret" | "mcp-permission";
