// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { JsonValue } from "../serde_json/JsonValue";
import type { Severity } from "./Severity";

/**
 * A single audit finding.
 *
 * `component_id` is `None` when the finding is produced by the scanner
 * (which doesn't know the component identity); the upsert layer fills
 * it in before persisting the row.
 */
export type Finding = { 
/**
 * Stable, deterministic id derived from
 * `sha256(component_path || category || pattern_name || matched_byte_range)`.
 * Persisted as `aseye-finding-<sha256-prefix>`.
 */
id: string, 
/**
 * Owning component URI. Populated by the upsert layer; the scanner
 * itself leaves this as `None` because it doesn't know identity.
 */
componentId: string | null, category: Category, 
/**
 * Name of the pattern that fired (e.g. `anthropic-key`,
 * `github-pat-classic`). Stable across releases - used by the
 * suppression table as a join key.
 */
pattern: string, severity: Severity, 
/**
 * Where in the parsed component the match was found. `body` for
 * the markdown body; a JSON pointer (`/mcpServers/github/env/GH_TOKEN`)
 * for structured leaves.
 */
sourceLabel: string, 
/**
 * 1-based line number inside the source string when known. The
 * scanner only computes this for the markdown body, not for JSON
 * leaves (where lines mean little after parsing).
 */
line: number | null, 
/**
 * Redacted preview - first 8 + ellipsis + last 4 chars of the
 * matched value (or first 4 + ellipsis + last 2 if total length
 * < 16). NEVER contains the secret in full.
 */
redactedPreview: string, 
/**
 * Unix epoch milliseconds when the finding was detected.
 */
detectedAt: bigint, 
/**
 * Structured evidence captured by the audit rule.
 *
 * Phase 7.1 secret findings leave this as `None` - their
 * (`pattern`, `redacted_preview`, `source_label`) triple already
 * fully describes the match.
 *
 * Phase 7.2 MCP permission findings populate it with a small JSON
 * object describing the inferred posture (e.g. host + database for
 * Postgres, repo scope for GitHub, package name for filesystem).
 * This stays out of the secret path - no credentials, no full
 * connection strings, no token values.
 *
 * Wire form: an `unknown | null` on the TS side via `ts-rs`'s
 * `serde-json-impl` feature.
 */
evidence: JsonValue | null, };
