// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit severity bucket. The Security UI sorts findings by severity
 * descending: `Critical` first, then `High`, `Medium`, `Low`.
 */
export type Severity = "low" | "medium" | "high" | "critical";
